project_id = "freelas-vagas-design"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[auth]
enabled = true
site_url = "https://vagasdesign.com.br"
additional_redirect_urls = [
  "https://vagasdesign.com.br/auth/callback",
  "https://www.vagasdesign.com.br/auth/callback",
  "https://freelas-vagas-design.vercel.app/auth/callback",
  "https://freelas-vagas-design-git-staging-vdveiculos.vercel.app/auth/callback",
  "http://localhost:3000/auth/callback",
]
enable_signup = true
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits"
jwt_expiry = 3600

[auth.rate_limit]
email_sent = 4
sign_in_sign_ups = 10
token_verifications = 10
token_refresh = 100

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.vector]
enabled = false
